* Fix LVM/RAID probing in the absence of /boot/grub/device.map   (LP: #525085, #527401). * Backport my upstream patch to copy .mo files from /usr/share/locale to   match where 'make install' puts them (LP: #537998). * Look for .mo files in /usr/share/locale-langpack as well, in preference   (LP: #537998). * Don't generate /boot/grub/device.map during grub-mkconfig (we already   suppressed it during grub-install, but then grub-mkconfig generated it   shortly afterwards, producing confusing results). * Don't run /etc/grub.d/README, even if it somehow ended up being   executable (LP: #537123).

diff --git a/debian/patches/962_no_device_map.diff b/debian/patches/962_no_device_map.diff
--- a/debian/patches/962_no_device_map.diff
+++ b/debian/patches/962_no_device_map.diff
@@ -1,9 +1,9 @@
 Ubuntu: Don't generate a device map by default.
 
-diff -Nur -x '*.orig' -x '*~' no-device-map/util/grub-install.in no-device-map.new/util/grub-install.in
---- no-device-map/util/grub-install.in	2010-01-13 11:56:17.000000000 +0000
-+++ no-device-map.new/util/grub-install.in	2010-01-13 11:57:33.000000000 +0000
-@@ -38,7 +38,6 @@
+diff -Nur -x '*.orig' -x '*~' grub2/util/grub-install.in grub2.new/util/grub-install.in
+--- grub2/util/grub-install.in	2010-03-22 14:11:42.000000000 +0000
++++ grub2.new/util/grub-install.in	2010-03-22 16:23:14.000000000 +0000
+@@ -39,7 +39,6 @@
  else
      grub_mkimage=${bindir}/`echo grub-mkelfimage | sed ${transform}`
  fi
@@ -11,7 +11,7 @@ diff -Nur -x '*.orig' -x '*~' no-device-map/util/grub-install.in no-device-map.n
  grub_probe=${sbindir}/`echo grub-probe | sed ${transform}`
  grub_editenv=${bindir}/`echo grub-editenv | sed ${transform}`
  rootdir=
-@@ -73,7 +72,6 @@
+@@ -74,7 +73,6 @@
                            instead of the root directory
    --grub-setup=FILE       use FILE as grub-setup
    --grub-mkimage=FILE     use FILE as grub-mkimage
@@ -19,7 +19,7 @@ diff -Nur -x '*.orig' -x '*~' no-device-map/util/grub-install.in no-device-map.n
    --grub-probe=FILE       use FILE as grub-probe
    --no-floppy             do not probe any floppy drive
    --recheck               probe a device map even if it already exists
-@@ -114,7 +112,7 @@
+@@ -124,7 +122,7 @@
      --grub-mkimage=*)
  	grub_mkimage=`echo "$option" | sed 's/--grub-mkimage=//'` ;;
      --grub-mkdevicemap=*)
@@ -28,7 +28,7 @@ diff -Nur -x '*.orig' -x '*~' no-device-map/util/grub-install.in no-device-map.n
      --grub-probe=*)
  	grub_probe=`echo "$option" | sed 's/--grub-probe=//'` ;;
      --no-floppy)
-@@ -199,14 +197,6 @@
+@@ -209,14 +207,6 @@
      exit 1
  fi
  
@@ -43,7 +43,7 @@ diff -Nur -x '*.orig' -x '*~' no-device-map/util/grub-install.in no-device-map.n
  # Create the GRUB directory if it is not present.
  test -d "$bootdir" || mkdir "$bootdir" || exit 1
  test -d "$grubdir" || mkdir "$grubdir" || exit 1
-@@ -216,22 +206,14 @@
+@@ -226,22 +216,14 @@
      rm -f $device_map
  fi
  
@@ -73,3 +73,40 @@ diff -Nur -x '*.orig' -x '*~' no-device-map/util/grub-install.in no-device-map.n
  fi
  
  # Copy the GRUB images to the GRUB directory.
+diff -Nur -x '*.orig' -x '*~' grub2/util/grub-mkconfig.in grub2.new/util/grub-mkconfig.in
+--- grub2/util/grub-mkconfig.in	2010-03-22 16:23:13.000000000 +0000
++++ grub2.new/util/grub-mkconfig.in	2010-03-22 16:23:57.000000000 +0000
+@@ -31,7 +31,6 @@
+ grub_cfg=""
+ grub_mkconfig_dir=${sysconfdir}/grub.d
+ 
+-grub_mkdevicemap=${sbindir}/`echo grub-mkdevicemap | sed ${transform}`
+ grub_probe=${sbindir}/`echo grub-probe | sed ${transform}`
+ 
+ # Usage: usage
+@@ -96,14 +95,6 @@
+   fi
+ fi
+ 
+-set $grub_mkdevicemap dummy
+-if test -f "$1"; then
+-    :
+-else
+-    echo "$1: Not found." 1>&2
+-    exit 1
+-fi
+-
+ set $grub_probe dummy
+ if test -f "$1"; then
+     :
+@@ -114,10 +105,6 @@
+ 
+ mkdir -p ${grub_prefix}
+ 
+-if test -e ${grub_prefix}/device.map ; then : ; else
+-  ${grub_mkdevicemap}
+-fi
+-
+ # Device containing our userland.  Typically used for root= parameter.
+ GRUB_DEVICE="`${grub_probe} --target=device /`"
+ GRUB_DEVICE_UUID="`${grub_probe} --device ${GRUB_DEVICE} --target=fs_uuid 2> /dev/null`" || true
